# Generated by Django 4.2.6 on 2024-01-20 07:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("brand", models.CharField(db_index=True, max_length=128)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "brand",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=64, verbose_name="name")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{8,15}$"
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(max_length=512, verbose_name="address")),
            ],
            options={
                "verbose_name": "customer",
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="ProductName"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("price", models.IntegerField(verbose_name="ProductPrice")),
                (
                    "location",
                    models.PositiveIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        default=1,
                        verbose_name="Location",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Brand",
                        to="store.brand",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Category",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
                "ordering": ("-created",),
            },
        ),
    ]
