# Generated by Django 4.2.6 on 2023-11-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "brand",
                    models.CharField(max_length=128, unique=True, verbose_name="Brand"),
                ),
            ],
            options={
                "verbose_name": "brand",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Category"
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="ProductName"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("price", models.IntegerField(verbose_name="ProductPrice")),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.brand",
                        verbose_name="Brand_id",
                    ),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                        verbose_name="Category_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
            },
        ),
    ]
