# Generated by Django 4.2.6 on 2023-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_brand_id_alter_product_category_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=1,
                verbose_name="Location",
            ),
        ),
    ]
