# Generated by Django 4.2.6 on 2023-11-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_brand_id_alter_product_category_id"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="Product",
            ),
        ),
    ]
